
python:
	@#python 02_10_search.py
	@#python 02_11_search_expand.py
	@#python 02_12_search_policy.py
	@#python 02_14_search_astar.py
	@#python 02_19_search_dp.py
	@#python 02_20_search_optimum.py
	python 02_21_search_turnleft_policy.py
